spring.application.name=server

# App
spring.application.name=napih-server

# H2 Database
spring.datasource.url=jdbc:h2:mem:napihdb
spring.datasource.driver-class-name=org.h2.Driver
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

# Actuator
management.endpoints.web.exposure.include=health,info